# Generated by Django 4.2.3 on 2024-03-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiltle', models.CharField(max_length=512)),
                ('year', models.SmallIntegerField()),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('genre', models.CharField(max_length=128)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
            ],
        ),
    ]
