# Generated by Django 4.2.3 on 2024-03-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk', '0003_genre_alter_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='kinopoisk.genre'),
        ),
    ]
