# Generated by Django 4.2.3 on 2024-03-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk', '0005_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='kinopoiskID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
